// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjePHzTljRMrcAy00Sp5AZ47xsMzhZTmQ',
    appId: '1:105422922840:web:106e4676c5820ea942962d',
    messagingSenderId: '105422922840',
    projectId: 'famio-project',
    authDomain: 'famio-project.firebaseapp.com',
    storageBucket: 'famio-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzusKsfuM3pvzA-RaM9A4GxBppZcI17xw',
    appId: '1:105422922840:android:f3697aa9e42b1abb42962d',
    messagingSenderId: '105422922840',
    projectId: 'famio-project',
    storageBucket: 'famio-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4tELNoXRg_ZOJ61hokUM2cRaXnhc-yE8',
    appId: '1:105422922840:ios:e1b5bbb8c4dcbdd642962d',
    messagingSenderId: '105422922840',
    projectId: 'famio-project',
    storageBucket: 'famio-project.firebasestorage.app',
    iosBundleId: 'com.example.famioproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4tELNoXRg_ZOJ61hokUM2cRaXnhc-yE8',
    appId: '1:105422922840:ios:e1b5bbb8c4dcbdd642962d',
    messagingSenderId: '105422922840',
    projectId: 'famio-project',
    storageBucket: 'famio-project.firebasestorage.app',
    iosBundleId: 'com.example.famioproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjePHzTljRMrcAy00Sp5AZ47xsMzhZTmQ',
    appId: '1:105422922840:web:13f4e4d57fcc4fb442962d',
    messagingSenderId: '105422922840',
    projectId: 'famio-project',
    authDomain: 'famio-project.firebaseapp.com',
    storageBucket: 'famio-project.firebasestorage.app',
  );
}
